server:
   port: 8080
spring :
   application:
      name: gateway
   cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations: #跨域设置
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
    enabled: true
    register-with-eureka: false  #是否注册到服务中心
    fetch-registry: false #是否获取注册列表信息


logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO