server:
   port: 8080
spring :
   application:
      name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
    register-with-eureka: true  #是否注册到服务中心
    fetch-registry: true #是否获取注册列表信息


logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO