server:
   port: 8090
spring :
   application:
      name: demo
log:
  auto:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
    register-with-eureka: true

logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO