server:
   port: 8090
spring :
   application:
      name: demo
   cloud:
     loadbalancer:
       ribbon:
         enabled: false

log:
  auto:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
    enabled: true




logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO