server:
   port: 8090
spring :
   application:
      name: spring-demo-8090
   cloud:
     loadbalancer:
       ribbon:
         enabled: false
   redis:
     redisson:
       file: classpath:redisson.yaml
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/console
     username: root
     password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.whh.springboot.springdemo.dto

#自定义日志组件
log:
  auto:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
    enabled: true
    register-with-eureka: false  #是否注册到服务中心
    fetch-registry: false #是否获取注册列表信息


logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO