spring:
  application:
    name: eureka
server:
  port: 8300
eureka:
  server:
    enable-self-preservation: false #防止由于Eureka的机制导致Client被错误显示在线 仅在开发环境使用
  client:
    service-url:
      defaultZone: http://localhost:8300/eureka/ #这便是此eureka server的应用注册地址
    register-with-eureka: true  #是否注册到服务中心
    fetch-registry: true #是否获取注册列表信息
